# Generated by Django 3.2.7 on 2022-06-07 05:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('promotioncode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotioncode',
            name='user',
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+6100000000', max_length=30, region=None, verbose_name='Phone Number'),
        ),
    ]
