# Generated by Django 3.2.7 on 2022-06-07 05:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('promotioncode', '0002_auto_20220607_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotioncode',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30, region=None, verbose_name='Phone Number'),
        ),
    ]
