# Generated by Django 3.2.7 on 2022-06-07 14:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('promotioncode', '0003_alter_promotioncode_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotioncode',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
